import Head from 'next/head';
import Image from 'next/image';
import PagesList from '../components/PagesList';
import { MongoClient } from 'mongodb';

export default function Home(props) {
    return (
        <div>
            <Head>
                <title>My Creations</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <PagesList pages={props.pages} />
        </div>
    );
}

export async function getStaticProps() {
    const url =
        'mongodb+srv://leko:mongodb@cluster0.1dbtc.mongodb.net/pages?retryWrites=true&w=majority';
    const client = await MongoClient.connect(url);
    const db = client.db();
    const pagesColl = db.collection('pages');
    const res = await pagesColl.find().toArray();
    client.close();
    return {
        props: {
            pages: res.map((e) => {
                return {
                    title: e.title,
                    description: e.description,
                    image: e.image,
                    link: e.link,
                    id: e._id.toString(),
                };
            }),
        },
    };
}
